### ISSUE TITLE
Problems with the boutique form page

### ISSUE THREAD

**Issue by poquirion** [SIMEXP/cbrain-plugins-psom#20]
- Keeps the inputs from the 13.5 version even if I switch to the beta version.
- Always tells me that the output entry is not a string, I then have to rewrite it, resubmit, and hope that it will be accepted as a string.

**Comment by glatard** [comment]
- The first issue should be solved, can you confirm?
- Can you give an example for the 2nd issue?

**Comment by poquirion** [comment]
Both problems went away with the disappearance of the 0.13.5 version. But we will have to keep an ete on that. I was perhaps linked to a caching process in my chromium browser.
