### ISSUE TITLE
Moving to singularity on guillimin

### ISSUE THREAD

**Issue by poquirion** [SIMEXP/cbrain-plugins-psom#26]
I am having problems with docker on guillimin. Now that singulrity 2.2 is installed everywhere, it might be time to switch. Also, got a email from Briarée and they are looking into installing singularity too.

**Comment by glatard** [comment]
It would be very nice indeed. However, it would need some updates in CBRAIN core. Could you post the commands that you use to run Niak on Guillimin through Singularity?

**Comment by poquirion** [comment]
I am debugging the thing right now, But the command is:

```
/home/poq/gsf-624-aa/quarantaine/singularity_images/bin/niak niak-boss-0.17.0
```

The thing is to put the bin dir in your path...

**Comment by poquirion** [comment]
Well I just realized that the previous command is interactive. I will add an option that will be equivalent to niak_cmd. It will be something like 

```
path/bin/niak niak-boss-0.17.0 --psom_worker -d [PATH] -w [NUMBER]
```
