### ISSUE TITLE
Support for BIDS

### ISSUE THREAD

**Issue by glatard** [SIMEXP/cbrain-plugins-psom#8]
- [x] BIDS support in PSOM
- [x] BIDS support in CBRAIN: view (list files, print validation errors).

**Comment by glatard** [comment]
CBRAIN now has a BIDS validator embedded.

**Comment by glatard** [comment]
The BIDS validator is also available in the "QC panel" of BIDS datasets so that datasets can be tagged according to the result of the validation. The same concept could be used for other pre-launch validations, e.g. parameter files (see update in #13).

**Comment by glatard** [comment]
To be tested using `simexp/niak-boss:beta`

**Comment by poquirion** [comment]
Its been integrated an it works in the test environment. Now waiting for a test on the Main CBRAIN platform.

**Comment by poquirion** [comment]
Working!
